services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cpd_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  api1:
    image: nnrea/api
    container_name: api1

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cpd_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_RABBITMQ_HOST: rabbitmq
      SERVER_PORT: 8080

    depends_on:
      - mysql
      - rabbitmq

 api2:
    image: nnrea/apiprueba
    container_name: api2
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cpd_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_RABBITMQ_HOST: rabbitmq
      SERVER_PORT: 8080
    depends_on:
      - mysql
      - rabbitmq

  haproxy:
    image: haproxy:2.7
    container_name: haproxy
    ports:
      - "80:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - api1
      - api2

  disk:
    image: nnrea/disk
    container_name: disk
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq

  instance:
    image: nnrea/instance
    container_name: instance
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq

volumes:
  mysql_data: